### ISSUE TITLE
AlpineComponent is actually the component's data

### ISSUE THREAD

**Issue by rehhouari** [LeanAdmin/alpine-typescript#6]
I've looked more in the source and turns out that was named to be AlpineComponent, is only the data of that component,
The `Component {}` type in Alpine.js source is different, and yesterday we used it on methods of the `Alpine` type.
This leave us with 3 types:

1. `Alpine` aka window.Alpine
2. `Component` actual Alpine component
3. `ComponentData` which contain the magic helpers and other user data.

I realized this is a breaking change since it renames types, so I didn't make a pull  request.

What do you think? If you want to keep it like it is now it works great, the only affected part is types used by plugins-which is what I'm using it on.
If so, I can put up another package with types only.

I already wrote the types out:

<details>

```ts
// window.Alpine type
export declare interface Alpine {
	version: string;
	pauseMutationObserver: boolean;
	magicProperties: { [name: string]: (el: HTMLElement) => void };
	ignoreFocusedForValueBinding: boolean;
	onComponentInitializeds: Array<(component: Component) => void>;
	onBeforeComponentInitializeds: Array<(component: Component) => void>;
	onComponentInitialized: (
		callback: (component: Component) => void
	) => void;
	onBeforeComponentInitialized: (
		callback: (component: Component) => void
	) => void;
	listenForNewUninitializedComponentsAtRunTime: () => undefined;
	discoverUninitializedComponents: (
		callback: (rootEl: HTMLElement) => void,
		el?: HTMLElement
	) => void;
	discoverComponents: (callback: (rootEl: HTMLElement) => void) => void;
	start: () => void;
	addMagicProperty: (
		name: string,
		callback: ($el: HTMLElement) => void
	) => void;
	clone: (component: Component, newEl: HTMLElement) => void;

	[key: string]: any;
}

// Actual Alpine Component{} type. will be accessed by plugins.
export declare interface Component {
	$el: HTMLElement;
	$data: ProxyConstructor;
	$nextTickStack: CallableFunction[];
	$showDirectiveStack: any[];
	$watchers: { [name: string]: CallableFunction };
	unobservedData: ComponentData;
	getUnobservedData: () => ComponentData;
	updateElements: (rootEl: HTMLElement, extraVars?: () => {}) => void;
	updateElement: (el: HTMLElement, extraVars?: () => {}) => void;
	evaluateReturnExpression: (
		el: HTMLElement,
		expression: string,
		extraVars?: () => {}
	) => void;
	[key: string]: any;
}

// The data that you can access within a component.
export declare abstract class ComponentData {
	/** Retrieve the root component DOM node. */
	$el: HTMLElement;
	/** Retrieve DOM elements marked with x-ref inside the component. */
	$refs: {
		[name: string]: HTMLElement;
	};
	/** Retrieve the native browser "Event" object within an event listener. */
	$event: Event;
	/** Create a CustomEvent and dispatch it using .dispatchEvent() internally. */
	$dispatch: (event: string, data: object) => void;
	/** Execute a given expression AFTER Alpine has made its reactive DOM updates. */
	$nextTick: (callback: (_: any) => void) => void;
	/** Will fire a provided callback when a component property you "watched" gets changed. */
	$watch: (property: string, callback: (value: any) => void) => void;
	[key: string]: any;
}
```
</details>

**Comment by stancl** [comment]
Open a PR with the added type being called something like `ComponentController` or `ComponentHandler`. The `ComponentData` should always be named `Component`, because most people only ever interact with that.

**Comment by rehhouari** [comment]
Alright! Also, one thing, what's the use case for members of `AlpineComponent` being optional?
I've got some errors about them so I had to use the null-safe operator, even though it always have those properties.
Even in here: https://github.com/LeanAdmin/alpine-typescript/blob/5104b5c62df97c7564cf5c869ef2a30befb43bbc/src/index.ts#L98-L100

It's used without the operator and the IDE gives an error for `$el` being possibly undefined.

**Comment by stancl** [comment]
If they weren't optional, you'd have to define the methods in class components: https://github.com/LeanAdmin/alpine-typescript#class-components

I don't have any IDE errors when working on this project, so that might be editor config

**Comment by rehhouari** [comment]
I see, I'm going to use class components, i think [definite assignment assertion](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#definite-assignment-assertions) is the alternative here. It tells typescript that these values are indeed assigned even though it wasn't done by us, which is the case here. thoughts?

**Comment by rehhouari** [comment]
Also, `component()` function checks if the class is `instanceof AlpineComponent`. I want to extend `AlpineComponent` to add more magic helpers. But it fail to register it because obviously the component isn't an instance of `AlpineComponent` but `ExtendedAlpineComponent`

is there a way around this or I have to copy the component function changing that line for this case?

**Comment by stancl** [comment]
instanceof supports inheritance

> definite assignment assertion

How would you do that in a class?

**Comment by rehhouari** [comment]
instanceof supports inheritance

oh i get why it didn't now, I was extending my own type not one provided by this package. Sorry for that I'm still new to JS in general

> definite assignment assertion

How would you do that in a class?

Simply by replacing `?` with `!`
`$el!: HTMLElement;`
